POST http://localhost:8080/api/login
Content-Type: application/json

{
  "password": "root",
  "number": "1001"


}

> {% client.global.set("token",response.headers.valueOf("authorization")); %}
###

GET http://localhost:8080/api/teacher/index
Authorization: {{token}}

###
POST http://localhost:8080/api/teacher/course
Content-Type: application/json
Authorization: {{token}}

{
  "name": "java"
}

###
POST http://localhost:8080/api/teacher/direction
Content-Type: application/json
Authorization: {{token}}

{
   "name":"小程序"
}

###
POST http://localhost:8080/api/teacher/student
Content-Type: application/json
Authorization: {{token}}

{
  "user": {
    "name": "张三",
    "number": "2017214215"
  }
}

###
POST http://localhost:8080/api/teacher/preStudent
Content-Type: application/json
Authorization: {{token}}

{
  "user": {
    "number": "2017214215"
  }
}

###
GET  http://localhost:8080/api/admin/teachers
Authorization: {{token}}

###
POST http://localhost:8080/api/admin/teacher
Content-Type: application/json
Authorization: {{token}}

{
  "user": {
  "number": "201111111",
  "name": "王五"}
}

###
GET  http://localhost:8080/api/admin/index
Authorization: {{token}}

###